apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: ingress-nginx
    meta.helm.sh/release-namespace: ingress-nginx
    metallb.universe.tf/ip-allocated-from-pool: kind-ipv4-pool
  creationTimestamp: "2026-02-26T11:32:26Z"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.14.3
    helm.sh/chart: ingress-nginx-4.14.3
  name: ingress-nginx-controller
  namespace: ingress-nginx
  resourceVersion: "16437"
  uid: 7af4c5b9-9eed-471b-827c-3f0d56b40ec2
spec:
  loadBalancerIP: 172.18.255.200
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.8.60
  clusterIPs:
  - 10.96.8.60
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    nodePort: 32461
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    nodePort: 32190
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.18.255.200
      ipMode: VIP
