apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: student-reg
type: Opaque
stringData:
  username: postgres
  password: postgres
  database: studentreg
  database_url: postgresql://postgres:postgres@postgres:5432/studentreg
  flyway_url: jdbc:postgresql://postgres:5432/studentreg
