apiVersion: v1
kind: Service
metadata:
  name: student-reg
  labels:
    app: student-reg
spec:
  selector:
    app: student-reg
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
