apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: student-reg
  namespace: student-reg
spec:
  ingressClassName: nginx
  rules:
  - host: student.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: student-reg
            port:
              number: 80
