resources:
  - ../../base
  - ingress.yaml

namespace: student-reg-dev

images:
  - name: ghcr.io/min2max-m/student-reg
    newName: ghcr.io/min2max-m/student-reg
    newTag: sha-6ad9f3a

patches:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: postgres
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/selector
        value:
          matchLabels:
            app: student-reg
            env: dev
            tier: db
